/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _GPIO_REGS_H_
#define _GPIO_REGS_H_

// Block name           : gpio
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define GPIO_O_OFFS 0
#define GPIO_OE_OFFS 4
#define GPIO_I_OFFS 8

/*******************************************************************************
*                                      O                                       *
*******************************************************************************/

// GPIO output register

// Field: O  Access: RW
#define GPIO_O_LSB  0
#define GPIO_O_BITS 8
#define GPIO_O_MASK 0xff

/*******************************************************************************
*                                      OE                                      *
*******************************************************************************/

// GPIO output enable register

// Field: OE  Access: RW
#define GPIO_OE_LSB  0
#define GPIO_OE_BITS 8
#define GPIO_OE_MASK 0xff

/*******************************************************************************
*                                      I                                       *
*******************************************************************************/

// GPIO input register

// Field: I  Access: ROV
#define GPIO_I_LSB  0
#define GPIO_I_BITS 8
#define GPIO_I_MASK 0xff

#endif // _GPIO_REGS_H_
