/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _TIMER_REGS_H_
#define _TIMER_REGS_H_

// Block name           : timer
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define TIMER_TIME_OFFS 0
#define TIMER_TIMEH_OFFS 4
#define TIMER_TIMECMP0_OFFS 8
#define TIMER_TIMECMP0H_OFFS 12
#define TIMER_TIMECMP1_OFFS 16
#define TIMER_TIMECMP1H_OFFS 20
#define TIMER_SOFTIRQ_SET_OFFS 24
#define TIMER_SOFTIRQ_CLR_OFFS 28

/*******************************************************************************
*                                     TIME                                     *
*******************************************************************************/

// Read/write access to time counter, low half

// Field: TIME  Access: RWF
#define TIMER_TIME_LSB  0
#define TIMER_TIME_BITS 32
#define TIMER_TIME_MASK 0xffffffff

/*******************************************************************************
*                                    TIMEH                                     *
*******************************************************************************/

// Read/write access to time counter, high half

// Field: TIMEH  Access: RWF
#define TIMER_TIMEH_LSB  0
#define TIMER_TIMEH_BITS 32
#define TIMER_TIMEH_MASK 0xffffffff

/*******************************************************************************
*                                   TIMECMP0                                   *
*******************************************************************************/

// Counter compare value 0, low half

// Field: TIMECMP0  Access: RW
#define TIMER_TIMECMP0_LSB  0
#define TIMER_TIMECMP0_BITS 32
#define TIMER_TIMECMP0_MASK 0xffffffff

/*******************************************************************************
*                                  TIMECMP0H                                   *
*******************************************************************************/

// Counter compare value 0, high half

// Field: TIMECMP0H  Access: RW
#define TIMER_TIMECMP0H_LSB  0
#define TIMER_TIMECMP0H_BITS 32
#define TIMER_TIMECMP0H_MASK 0xffffffff

/*******************************************************************************
*                                   TIMECMP1                                   *
*******************************************************************************/

// Counter compare value 0, low half

// Field: TIMECMP1  Access: RW
#define TIMER_TIMECMP1_LSB  0
#define TIMER_TIMECMP1_BITS 32
#define TIMER_TIMECMP1_MASK 0xffffffff

/*******************************************************************************
*                                  TIMECMP1H                                   *
*******************************************************************************/

// Counter compare value 0, high half

// Field: TIMECMP1H  Access: RW
#define TIMER_TIMECMP1H_LSB  0
#define TIMER_TIMECMP1H_BITS 32
#define TIMER_TIMECMP1H_MASK 0xffffffff

/*******************************************************************************
*                                 SOFTIRQ_SET                                  *
*******************************************************************************/

// Set soft IRQs on write. Get soft IRQ status on read.

// Field: SOFTIRQ_SET  Access: RWF
#define TIMER_SOFTIRQ_SET_LSB  0
#define TIMER_SOFTIRQ_SET_BITS 2
#define TIMER_SOFTIRQ_SET_MASK 0x3

/*******************************************************************************
*                                 SOFTIRQ_CLR                                  *
*******************************************************************************/

// Clear soft IRQs on write. Get soft IRQ status on read.

// Field: SOFTIRQ_CLR  Access: RWF
#define TIMER_SOFTIRQ_CLR_LSB  0
#define TIMER_SOFTIRQ_CLR_BITS 2
#define TIMER_SOFTIRQ_CLR_MASK 0x3

#endif // _TIMER_REGS_H_
